### PR TITLE
fixes back button appearance according to .history() value

### LINKED ISSUE #543: .history(false) doesn't work for pie chart
According to [wiki](https://github.com/alexandersimoes/d3plus/wiki/Visualizations#history) this method should hide back button when .history() set to false.

However, it doesn't work in this case:
http://jsfiddle.net/v1fvhpvx/11/

### PR DESCRIPTION
**Pull request by azastupailo**
Just added another `if` statement which checks if `vars.history.value` is set to `true` and should draw the back button. Tested for the same type of viz mentioned in the issue.

Fixes #543

### CODE REVIEW

File: src/viz/helpers/ui/history.coffee [hunk 1]
```diff
@@ -8,13 +8,6 @@ module.exports = (vars) ->
 
   if !vars.small and vars.history.states.length > 0
```
Comment (davelandry) [inline src/viz/helpers/ui/history.coffee]: I think the code would be more succinct if this if statement was modified as such:
```js
if !vars.small and vars.history.value and vars.history.states.length > 0
```

The rest of the behavior should be able to stay the same.

**Comment by azastupailo** [comment]
Well, it's simpler than I expected. Updated the pull request.
